version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecsite
    ports:
      - "3306:3306"
    volumes:
      - ecsite-data:/var/lib/mysql # MySQLのデータを永続化する設定
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  ecsite-data:
